spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
server:
  port: 8088
  servlet:
    context-path: /api
qi:
  api:
    client:
      access-key: 9235bf9ad7215cd96a69301f0e577629
      secret-key: a24d28e2418520503dbf59820f61f9f0
      #  本地测试增加修改
      host: http://localhost:8090/api/
